apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: # --> Add
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: # --> Add
              servicePort: # --> Add
